export const GET_FAVOURITES_REQUEST = 'USER_FAVOURITES_REQUEST';
export const GET_FAVOURITES_SUCCESS = 'USER_FAVOURITES_SUCCESS';
export const GET_FAVOURITES_FAIL = 'USER_FAVOURITES_FAIL';

export const ADD_FAVOURITES_REQUEST = 'ADD_FAVOURITES_REQUEST';
export const ADD_FAVOURITES_SUCCESS = 'ADD_FAVOURITES_SUCCESS';
export const ADD_FAVOURITES_FAIL = 'ADD_FAVOURITES_FAIL';

export const REMOVE_FAVOURITES_REQUEST = 'REMOVE_FAVOURITES_REQUEST';
export const REMOVE_FAVOURITES_SUCCESS = 'REMOVE_FAVOURITES_SUCCESS';
export const REMOVE_FAVOURITES_FAIL = 'REMOVE_FAVOURITES_FAIL';
