export const GET_GENRE_REQUEST = 'GET_GENRE_REQUEST';
export const GET_GENRE_SUCCESS = 'GET_GENRE_SUCCESS';
export const GET_GENRE_FAIL = 'GET_GENRE_FAIL';

export const GET_GENRE_SPECIFIC_MOVIES_REQUEST =
  'GET_GENRE_SPECIFIC_MOVIES_REQUEST';
export const GET_GENRE_SPECIFIC_MOVIES_SUCCESS =
  'GET_GENRE_SPECIFIC_MOVIES_SUCCESS';
export const GET_GENRE_SPECIFIC_MOVIES_FAIL = 'GET_GENRE_SPECIFIC_MOVIES_FAIL';
