export const ALL_MOVIES_REQUEST = 'ALL_MOVIES_REQUEST';
export const ALL_MOVIES_SUCCESS = 'ALL_MOVIES_SUCCESS';
export const ALL_MOVIES_FAIL = 'ALL_MOVIES_FAIL';

export const CLEAR_ALL_ERRORS = 'CLEAR_ALL_ERRORS';
