export const ALL_MOVIES_REQUEST = 'ALL_MOVIES_REQUEST';
export const ALL_MOVIES_SUCCESS = 'ALL_MOVIES_SUCCESS';
export const ALL_MOVIES_FAIL = 'ALL_MOVIES_FAIL';

export const MOVIE_DETAILS_REQUEST = 'MOVIE_DETAILS_REQUEST';
export const MOVIE_DETAILS_SUCCESS = 'MOVIE_DETAILS_SUCCESS';
export const MOVIE_DETAILS_FAIL = 'MOVIE_DETAILS_FAIL';

export const MOVIES_BY_ACTOR_REQUEST = 'MOVIES_BY_ACTOR_REQUEST';
export const MOVIES_BY_ACTOR_SUCCESS = 'MOVIES_BY_ACTOR_SUCCESS';
export const MOVIES_BY_ACTOR_FAIL = 'MOVIES_BY_ACTOR_FAIL';

export const FETCH_MOVIES_BY_GENRE_REQUEST = 'FETCH_MOVIES_BY_GENRE_REQUEST';
export const FETCH_MOVIES_BY_GENRE_SUCCESS = 'FETCH_MOVIES_BY_GENRE_SUCCESS';
export const FETCH_MOVIES_BY_GENRE_FAIL = 'FETCH_MOVIES_BY_GENRE_FAIL';

export const CLEAR_ALL_ERRORS = 'CLEAR_ALL_ERRORS';
